version: '3.4'

services:
  db:
    build:
      context: .
      target: dellstore
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

  db_isolated:
    build:
      context: .
      target: dellstore_isolated
    restart: always
    ports:
      - 3456:5432
    environment:
      POSTGRES_DB: ${ISOLATED_DB_NAME}
      POSTGRES_USER: ${ISOLATED_DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_isolated_password
    secrets:
      - db_isolated_password
    volumes:
      - db_isolated_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
      - db_isolated
    build:
      context: .
      target: backend
      args:
        PYTHON_DEBUG: ${PYTHON_DEBUG}
    ports:
      - ${FLASK_PORT}:5000
      - 10001:10001
    restart: always
    env_file:
      - .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      ISOLATED_DB_PASSWORD_FILE: /run/secrets/db_isolated_password
    secrets:
      - db_password
      - db_isolated_password
    volumes:
      - ./:/app:cached

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

secrets:
  db_password:
    file: ./db_password
  db_isolated_password:
    file: ./db_isolated_password

volumes:
  db_data:
  db_isolated_data: